export const products = [
  {
    _id: "_65bb0vwa2",
    productName: "Product 1",
    price: "$99.89",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ihztrt4p7",
    productName: "Product 2",
    price: "$78.01",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ry78w9nqc",
    productName: "Product 3",
    price: "$78.04",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_9bml1sqa0",
    productName: "Product 4",
    price: "$42.51",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_fxtj2130f",
    productName: "Product 5",
    price: "$45.06",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_2rze5dfil",
    productName: "Product 6",
    price: "$41.02",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_uy1g54v3y",
    productName: "Product 7",
    price: "$91.93",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_djonj24ln",
    productName: "Product 8",
    price: "$41.31",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ka12myf1x",
    productName: "Product 9",
    price: "$33.79",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_zqag8qhum",
    productName: "Product 10",
    price: "$69.54",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_yw8elxk4h",
    productName: "Product 11",
    price: "$82.45",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ce8cr7vpi",
    productName: "Product 12",
    price: "$56.74",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ygwkaqcef",
    productName: "Product 13",
    price: "$49.83",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_2smdst2ej",
    productName: "Product 14",
    price: "$82.56",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_7f76cs7v0",
    productName: "Product 15",
    price: "$70.88",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_2qr423ooy",
    productName: "Product 16",
    price: "$68.22",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_fkg8e9mfy",
    productName: "Product 17",
    price: "$27.02",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_m06lwqfll",
    productName: "Product 18",
    price: "$34.89",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_w06mmhui1",
    productName: "Product 19",
    price: "$62.99",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_360k4ycms",
    productName: "Product 20",
    price: "$35.17",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_42kvgwibw",
    productName: "Product 21",
    price: "$89.01",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_lizqwpc4s",
    productName: "Product 22",
    price: "$79.80",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_kjjckaavp",
    productName: "Product 23",
    price: "$33.05",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ai8z7tyla",
    productName: "Product 24",
    price: "$85.53",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_8qmq15nge",
    productName: "Product 25",
    price: "$90.52",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_d9maur2xg",
    productName: "Product 26",
    price: "$81.86",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_bcfck6at7",
    productName: "Product 27",
    price: "$95.34",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_w15mupe3j",
    productName: "Product 28",
    price: "$98.90",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_iz8f80my4",
    productName: "Product 29",
    price: "$21.70",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_z85v6kozf",
    productName: "Product 30",
    price: "$36.58",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ke21m94hj",
    productName: "Product 31",
    price: "$72.97",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_kxcqji4ln",
    productName: "Product 32",
    price: "$13.35",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_kq2eraohd",
    productName: "Product 33",
    price: "$52.96",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_iojhrb7nx",
    productName: "Product 34",
    price: "$39.28",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_yjnubmvl4",
    productName: "Product 35",
    price: "$97.43",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_vrza68htq",
    productName: "Product 36",
    price: "$99.95",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ixaidsic3",
    productName: "Product 37",
    price: "$25.49",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_ikk6ouybc",
    productName: "Product 38",
    price: "$67.15",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_bb080wzk4",
    productName: "Product 39",
    price: "$49.61",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_c1bxaybuw",
    productName: "Product 40",
    price: "$39.60",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_98kkoo7ji",
    productName: "Product 41",
    price: "$75.89",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_t6nxferf8",
    productName: "Product 42",
    price: "$37.73",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_qco3qqe35",
    productName: "Product 43",
    price: "$81.87",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_2sziozcm6",
    productName: "Product 44",
    price: "$23.73",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_8tlpno5p1",
    productName: "Product 45",
    price: "$33.24",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_68lpddr6s",
    productName: "Product 46",
    price: "$61.65",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_dmnfrswku",
    productName: "Product 47",
    price: "$36.61",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_a60xia36u",
    productName: "Product 48",
    price: "$17.13",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_vqmkcwbay",
    productName: "Product 49",
    price: "$44.10",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_2tx5hwnli",
    productName: "Product 50",
    price: "$44.43",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_othklagt1",
    productName: "Product 51",
    price: "$74.17",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_iiakfzykz",
    productName: "Product 52",
    price: "$74.65",
    imageLink: "",
    largeImageLink: "",
  },
  {
    _id: "_690gbqlgq",
    productName: "Product 53",
    price: "$91.86",
    imageLink: "",
    largeImageLink: "",
  },
];
